# Configuración para CalenConnect API

# Configuración de la aplicación
calenconnect-api:
    port: 3000

# Configuración de conexión a Supabase
supabase:
    url: "https://example-supabase-url.supabase.co"
    key: "example-supabase-key"
